package com.springbootjpamysql.controller;

import org.hibernate.exception.DataException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.springbootjpamysql.model.User;
import com.springbootjpamysql.payload.UserDto;
import com.springbootjpamysql.repository.UserRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/api/v1") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path = "/create") // Map ONLY POST Requests
    public @ResponseBody String addNewUser(@RequestBody UserDto user) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(user.getName());
        n.setEmail(user.getEmail());
        userRepository.save(n);
        return "Created";
    }

    @PatchMapping(path = "/update") // Map ONLY POST Requests
    public @ResponseBody String updateUser(@RequestBody UserDto user) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setId(user.getId());
        n.setName(user.getName());
        n.setEmail(user.getEmail());
        if (userRepository.existsById(user.getId()))
            userRepository.save(n);
        else
            throw new DataException("User not found", null);
        return "Updated";
    }

    @DeleteMapping(path = "/delete/{id}") // Map ONLY POST Requests
    public @ResponseBody String deleteUser(@PathVariable Integer id) {
        User n = new User();
        n.setId(id);

        if (!userRepository.existsById(id))
            throw new DataException("User not found", null);
        else
            userRepository.delete(n);
        return "Deleted";
    }

    @GetMapping(path = "/get")
    public @ResponseBody User getUser(@RequestParam Integer id) {
        // This returns a JSON or XML with the users
        return userRepository.findById(id).get();
    }

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
